### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by coisino** [hongyaohongyao/smart_classroom_demo#10]
有几个bug，一个是原本十几秒的视频，到头了它不终止，还在继续执行，下边的时间都能到一分多。还有一个是播放暂停按钮好像不能用

**Comment by hongyaohongyao** [comment]
感谢您的建议：
1. 视频是循环播放的
2. 暂停只有在非实时播放（进度条不在最右端）有效，之后会进行修正😂
