### ISSUE TITLE
模型咨询

### ISSUE THREAD

**Issue by EpiphanyMelody** [hongyaohongyao/smart_classroom_demo#16]
我想使用自己的数据集通过alphapose的框架训练模型，再将训练好的模型替换本项目的halpe136_mobile.torchscript.pth模型，这种做法是可行的吗，如果可行的话，自己数据集的训练模型是否必须是halpe136呢，coco数据集训练模型可以吗

**Comment by hongyaohongyao** [comment]
模型是可以替换，但是coco数据集的点的数量和序号可能不兼容，除非你可以自己改源代码去取对应位置的关键点
