### ISSUE TITLE
一些报错

### ISSUE THREAD

**Issue by zhou-xiaoning** [hongyaohongyao/smart_classroom_demo#2]
大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
open_face_bank:  cannot unpack non-iterable NoneType object

还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))

**Comment by hongyaohongyao** [comment]
> 大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
> get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> open_face_bank: cannot unpack non-iterable NoneType object
> 
> 还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
> RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
> fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))

1.  resource/face_bank里面需要再创建一层文件夹，像下面这样，里面才是人脸信息，自动创建的好像少了一层 。另外也有可能是你之前注册的时候出错，人脸信息没创建全，需要把失败的数据手动删掉。
![image](https://user-images.githubusercontent.com/43579107/127827034-11677028-4484-4b76-80b5-34e14c274fbd.png)
2. 因为matplotlib效率比较低，所以课题专注度只会5秒绘制一次曲线；有些视频大小是不支持的，目前测试过的640x480、800x480可以，1280x720会报错；matplotlib最好就是3.2.2版本，其他版本不知道会有什么bug

**Comment by zhou-xiaoning** [comment]
> > 大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
> > get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> > open_face_bank: cannot unpack non-iterable NoneType object
> > 还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
> > RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
> > fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))
> 
> 1. resource/face_bank里面需要再创建一层文件夹，像下面这样，里面才是人脸信息，自动创建的好像少了一层 。另外也有可能是你之前注册的时候出错，人脸信息没创建全，需要把失败的数据手动删掉。
>    ![image](https://user-images.githubusercontent.com/43579107/127827034-11677028-4484-4b76-80b5-34e14c274fbd.png)
> 2. 因为matplotlib效率比较低，所以课题专注度只会5秒绘制一次曲线；有些视频大小是不支持的，目前测试过的640x480、800x480可以，1280x720会报错；matplotlib最好就是3.2.2版本，其他版本不知道会有什么bug

动态点名如何才可以签到成功？识别的准确率已经高于设置的阈值很久了，但还是一直不能签到上

**Comment by hongyaohongyao** [comment]
> > > 大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
> > > get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> > > open_face_bank: cannot unpack non-iterable NoneType object
> > > 还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
> > > RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
> > > fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))
> > 
> > 
> > 
> > 1. resource/face_bank里面需要再创建一层文件夹，像下面这样，里面才是人脸信息，自动创建的好像少了一层 。另外也有可能是你之前注册的时候出错，人脸信息没创建全，需要把失败的数据手动删掉。
> >    ![image](https://user-images.githubusercontent.com/43579107/127827034-11677028-4484-4b76-80b5-34e14c274fbd.png)
> > 2. 因为matplotlib效率比较低，所以课题专注度只会5秒绘制一次曲线；有些视频大小是不支持的，目前测试过的640x480、800x480可以，1280x720会报错；matplotlib最好就是3.2.2版本，其他版本不知道会有什么bug
> 
> 动态点名如何才可以签到成功？识别的准确率已经高于设置的阈值很久了，但还是一直不能签到上

进入到已签到列表就算签到成功

**Comment by zhou-xiaoning** [comment]
> > > > 大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
> > > > get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> > > > open_face_bank: cannot unpack non-iterable NoneType object
> > > > 还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
> > > > RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
> > > > fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))
> > > 
> > > 
> > > 
> > > 1. resource/face_bank里面需要再创建一层文件夹，像下面这样，里面才是人脸信息，自动创建的好像少了一层 。另外也有可能是你之前注册的时候出错，人脸信息没创建全，需要把失败的数据手动删掉。
> > >    ![image](https://user-images.githubusercontent.com/43579107/127827034-11677028-4484-4b76-80b5-34e14c274fbd.png)
> > > 2. 因为matplotlib效率比较低，所以课题专注度只会5秒绘制一次曲线；有些视频大小是不支持的，目前测试过的640x480、800x480可以，1280x720会报错；matplotlib最好就是3.2.2版本，其他版本不知道会有什么bug
> > 
> > 
> > 动态点名如何才可以签到成功？识别的准确率已经高于设置的阈值很久了，但还是一直不能签到上
> 
> 进入到已签到列表就算签到成功

一直进不去是哪里做的不对吗
![@BENQI}PXDYFV9K%5P)M80C](https://user-images.githubusercontent.com/65398227/127840938-1573ad0e-fc02-407f-9777-37e56c382e19.png)
![G1MB}8OR{PJLEQ`10D9A(TR](https://user-images.githubusercontent.com/65398227/127840948-5ca8d7eb-7a36-4884-9b68-4bfb3dfc9598.png)

**Comment by hongyaohongyao** [comment]
> > > > > 大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
> > > > > get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> > > > > open_face_bank: cannot unpack non-iterable NoneType object
> > > > > 还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
> > > > > RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
> > > > > fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))
> > > > 
> > > > 
> > > > 
> > > > 1. resource/face_bank里面需要再创建一层文件夹，像下面这样，里面才是人脸信息，自动创建的好像少了一层 。另外也有可能是你之前注册的时候出错，人脸信息没创建全，需要把失败的数据手动删掉。
> > > >    ![image](https://user-images.githubusercontent.com/43579107/127827034-11677028-4484-4b76-80b5-34e14c274fbd.png)
> > > > 2. 因为matplotlib效率比较低，所以课题专注度只会5秒绘制一次曲线；有些视频大小是不支持的，目前测试过的640x480、800x480可以，1280x720会报错；matplotlib最好就是3.2.2版本，其他版本不知道会有什么bug
> > > 
> > > 
> > > 动态点名如何才可以签到成功？识别的准确率已经高于设置的阈值很久了，但还是一直不能签到上
> > 
> > 
> > 进入到已签到列表就算签到成功
> 
> 一直进不去是哪里做的不对吗
> ![@BENQI}PXDYFV9K%5P)M80C](https://user-images.githubusercontent.com/65398227/127840938-1573ad0e-fc02-407f-9777-37e56c382e19.png)
> ![G1MB}8OR{PJLEQ`10D9A(TR](https://user-images.githubusercontent.com/65398227/127840948-5ca8d7eb-7a36-4884-9b68-4bfb3dfc9598.png)

你是不是自己改过代码？这个功能检测后会保留最好的匹配结果，改变阈值能动态调整签到列表。

**Comment by zhou-xiaoning** [comment]
> > > > > > 大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
> > > > > > get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> > > > > > open_face_bank: cannot unpack non-iterable NoneType object
> > > > > > 还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
> > > > > > RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
> > > > > > fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. resource/face_bank里面需要再创建一层文件夹，像下面这样，里面才是人脸信息，自动创建的好像少了一层 。另外也有可能是你之前注册的时候出错，人脸信息没创建全，需要把失败的数据手动删掉。
> > > > >    ![image](https://user-images.githubusercontent.com/43579107/127827034-11677028-4484-4b76-80b5-34e14c274fbd.png)
> > > > > 2. 因为matplotlib效率比较低，所以课题专注度只会5秒绘制一次曲线；有些视频大小是不支持的，目前测试过的640x480、800x480可以，1280x720会报错；matplotlib最好就是3.2.2版本，其他版本不知道会有什么bug
> > > > 
> > > > 
> > > > 动态点名如何才可以签到成功？识别的准确率已经高于设置的阈值很久了，但还是一直不能签到上
> > > 
> > > 
> > > 进入到已签到列表就算签到成功
> > 
> > 
> > 一直进不去是哪里做的不对吗
> > ![@BENQI}PXDYFV9K%5P)M80C](https://user-images.githubusercontent.com/65398227/127840938-1573ad0e-fc02-407f-9777-37e56c382e19.png)
> > ![G1MB}8OR{PJLEQ`10D9A(TR](https://user-images.githubusercontent.com/65398227/127840948-5ca8d7eb-7a36-4884-9b68-4bfb3dfc9598.png)
> 
> 你是不是自己改过代码？这个功能检测后会保留最好的匹配结果，改变阈值能动态调整签到列表。

改了代码，但点名这部分的功能没有改动，识别时准确率一直在65上下，所以就在运行的界面把识别的阈值调低了一点

**Comment by hongyaohongyao** [comment]
> > > > > > > 大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
> > > > > > > get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> > > > > > > open_face_bank: cannot unpack non-iterable NoneType object
> > > > > > > 还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
> > > > > > > RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
> > > > > > > fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 1. resource/face_bank里面需要再创建一层文件夹，像下面这样，里面才是人脸信息，自动创建的好像少了一层 。另外也有可能是你之前注册的时候出错，人脸信息没创建全，需要把失败的数据手动删掉。
> > > > > >    ![image](https://user-images.githubusercontent.com/43579107/127827034-11677028-4484-4b76-80b5-34e14c274fbd.png)
> > > > > > 2. 因为matplotlib效率比较低，所以课题专注度只会5秒绘制一次曲线；有些视频大小是不支持的，目前测试过的640x480、800x480可以，1280x720会报错；matplotlib最好就是3.2.2版本，其他版本不知道会有什么bug
> > > > > 
> > > > > 
> > > > > 动态点名如何才可以签到成功？识别的准确率已经高于设置的阈值很久了，但还是一直不能签到上
> > > > 
> > > > 
> > > > 进入到已签到列表就算签到成功
> > > 
> > > 
> > > 一直进不去是哪里做的不对吗
> > > ![@BENQI}PXDYFV9K%5P)M80C](https://user-images.githubusercontent.com/65398227/127840938-1573ad0e-fc02-407f-9777-37e56c382e19.png)
> > > ![G1MB}8OR{PJLEQ`10D9A(TR](https://user-images.githubusercontent.com/65398227/127840948-5ca8d7eb-7a36-4884-9b68-4bfb3dfc9598.png)
> > 
> > 
> > 你是不是自己改过代码？这个功能检测后会保留最好的匹配结果，改变阈值能动态调整签到列表。
> 
> 改了代码，但点名这部分的功能没有改动，识别时准确率一直在65上下，所以就在运行的界面把识别的阈值调低了一点

你下一份原版的代码重新试一下吧

**Comment by zhou-xiaoning** [comment]
> > > > > > > > 大佬大佬，我又遇到了一些问题，人脸注册之后再次进入系统，想要测试点名功能，但打开摄像头时会卡死退掉
> > > > > > > > get_known_faces_data 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> > > > > > > > open_face_bank: cannot unpack non-iterable NoneType object
> > > > > > > > 还有一个，专注度分析的功能，测试本地视频时，视频也比较小，那些分析的曲线画不出来，会满屏的报错，说画的图片太多了
> > > > > > > > RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
> > > > > > > > fig = plt.figure(figsize=(self.plot_base_h * aspect, self.plot_base_h))
> > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 1. resource/face_bank里面需要再创建一层文件夹，像下面这样，里面才是人脸信息，自动创建的好像少了一层 。另外也有可能是你之前注册的时候出错，人脸信息没创建全，需要把失败的数据手动删掉。
> > > > > > >    ![image](https://user-images.githubusercontent.com/43579107/127827034-11677028-4484-4b76-80b5-34e14c274fbd.png)
> > > > > > > 2. 因为matplotlib效率比较低，所以课题专注度只会5秒绘制一次曲线；有些视频大小是不支持的，目前测试过的640x480、800x480可以，1280x720会报错；matplotlib最好就是3.2.2版本，其他版本不知道会有什么bug
> > > > > > 
> > > > > > 
> > > > > > 动态点名如何才可以签到成功？识别的准确率已经高于设置的阈值很久了，但还是一直不能签到上
> > > > > 
> > > > > 
> > > > > 进入到已签到列表就算签到成功
> > > > 
> > > > 
> > > > 一直进不去是哪里做的不对吗
> > > > ![@BENQI}PXDYFV9K%5P)M80C](https://user-images.githubusercontent.com/65398227/127840938-1573ad0e-fc02-407f-9777-37e56c382e19.png)
> > > > ![G1MB}8OR{PJLEQ`10D9A(TR](https://user-images.githubusercontent.com/65398227/127840948-5ca8d7eb-7a36-4884-9b68-4bfb3dfc9598.png)
> > > 
> > > 
> > > 你是不是自己改过代码？这个功能检测后会保留最好的匹配结果，改变阈值能动态调整签到列表。
> > 
> > 
> > 改了代码，但点名这部分的功能没有改动，识别时准确率一直在65上下，所以就在运行的界面把识别的阈值调低了一点
> 
> 你下一份原版的代码重新试一下吧

还是不行的呀

**Comment by hongyaohongyao** [comment]
你干脆把阈值设成1看看啥情况呗，也注意看看控制台有没有报错

**Comment by zhou-xiaoning** [comment]
> 你干脆把阈值设成1看看啥情况呗，也注意看看控制台有没有报错

一直在识别，但不能签到成功，会显示让直视摄像头，偶尔的时候会出现卡死的现象，然后会报错，一般出现在转头或低头的时候，重新启动摄像头就又可以识别了
![image](https://user-images.githubusercontent.com/65398227/127880412-17c27f3b-f2b6-440a-997b-82b595f18c1a.png)

**Comment by hongyaohongyao** [comment]
> > 你干脆把阈值设成1看看啥情况呗，也注意看看控制台有没有报错
> 
> 一直在识别，但不能签到成功，会显示让直视摄像头，偶尔的时候会出现卡死的现象，然后会报错，一般出现在转头或低头的时候，重新启动摄像头就又可以识别了
> ![image](https://user-images.githubusercontent.com/65398227/127880412-17c27f3b-f2b6-440a-997b-82b595f18c1a.png)

现在可以了，两个bug均已修复，感谢你对项目的贡献😊
