### ISSUE TITLE
opencv 相关库报错

### ISSUE THREAD

**Issue by fly361** [hongyaohongyao/smart_classroom_demo#48]
QObject::moveToThread: Current thread (0x55c44bf87060) is not the object's thread (0x55c4553307a0).
Cannot move to target thread (0x55c44bf87060)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/root/miniconda3/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

你好，请问这个错误如何解决呢？在网上找了很多办法也没有解决。这似乎是opencv库的问题？你们没有遇到这个问题吗?

**Comment by fly361** [comment]
问题解决了，我原来是用autoDL跑的，这是linux系统，所以会出现问题，用windows本地的系统跑就不会有问题。

**Comment by Bill110110** [comment]
linux系统只要把opencv的版本降级一下就好了，亲测可用
