### ISSUE TITLE
动作识别相关问题

### ISSUE THREAD

**Issue by coisino** [hongyaohongyao/smart_classroom_demo#5]
还有一个问题，动作识别要是添加新的动作的话，要修改一下网络结构然后重新训练，请问有相关的训练的代码嘛

**Comment by hongyaohongyao** [comment]
只需要重新训练一个对关键点的逻辑回归分类器就行了，然后像权重classroom_action_lr_front_v2.torchscript.pth那样使用。训练的话我是这样做的
1. 拍摄单人的动作视频
2. 用opencv抽转保存成图片
3. 用Alphapose生成关键点数据
4. 读取关键点数据预处理然后使用逻辑回归直接训练
5. 最后转换成torchscript代码使用
这个训练成本相对较低，不需要系统的训练过程，你可以自己写代码处理，甚至用sklearn分类也行。
