### ISSUE TITLE
yolov5s cpu版本转torchscript 问题

### ISSUE THREAD

**Issue by coisino** [hongyaohongyao/smart_classroom_demo#6]
我在官网上下载上cpu版本的yolov5s模型，可以运行，但当我尝试转成torchscript时报错了
使用script方法：yolov5_s = torch.jit.script(model) 报错：
  RuntimeError: Can't redefine method: forward on class: __torch__.models.common.SPP (of Python compilation unit at: 000001CB38993690)
使用trace方法的话，把图片转为tensor类型的之后，也报错了。。。

**Comment by Hammer-888** [comment]
转了之后报错这个 RuntimeError: The size of tensor a (60) must match the size of tensor b (80) at non-singleton dimension 2
