### ISSUE TITLE
运行速度

### ISSUE THREAD

**Issue by 3019234115** [hongyaohongyao/smart_classroom_demo#8]
运行的时候延迟过大，很卡。已经使用GPU了，但是仍旧很不理想，请问是因为帧率过大吗？还是模型检测就需要这么久

**Comment by hongyaohongyao** [comment]
> 运行的时候延迟过大，很卡。已经使用GPU了，但是仍旧很不理想，请问是因为帧率过大吗？还是模型检测就需要这么久

延迟是因为抽帧。残血2060最好把视频帧率降到12帧左右，3060可以使用30帧。动态点名需要自己编译gpu版的dlib

**Comment by 3019234115** [comment]
我看了是12帧，但是作弊检测过一会就会卡死无响应
本地视频目录已创建: resource/videos/cheating_detection
本地视频目录已创建: resource/videos/class_concentration
本地视频目录已创建: resource/videos/dynamic_attendance
本地视频目录已创建: resource/face_bank
created: <pipeline_module.video_modules.VideoModule object at 0x000001C88BE9C908>
created: <pipeline_module.yolo_modules.YoloV5Module object at 0x000001C88BE9CB48>
C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\site-packages\torch\nn\modules\module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return forward_call(*input, **kwargs)
created: <pipeline_module.pose_modules.AlphaPoseModule object at 0x000001C8A57E3EC8>
created: <pipeline_module.classroom_action_module.CheatingActionModule object at 0x000001C8A5910E08>
created: <pipeline_module.vis_modules.CheatingDetectionVisModule object at 0x000001C8A591A9C8>
starting modules <pipeline_module.yolo_modules.YoloV5Module object at 0x000001C88BE9CB48>
starting modules <pipeline_module.pose_modules.AlphaPoseModule object at 0x000001C8A57E3EC8>
starting modules <pipeline_module.classroom_action_module.CheatingActionModule object at 0x000001C8A5910E08>
starting modules <pipeline_module.vis_modules.CheatingDetectionVisModule object at 0x000001C8A591A9C8>
视频源帧率:  30.0
Exception ignored in: <function Image.__del__ at 0x000001C8FEE22948>
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001C8FEE22948>
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001C8FEE22948>
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001C8FEE22948>
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001C8FEE22948>
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001C8FEE22948>
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001C8FEE22948>
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001C8FEE22948>
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread

**Comment by hongyaohongyao** [comment]
> 我看了是12帧，但是作弊检测过一会就会卡死无响应
> 本地视频目录已创建: resource/videos/cheating_detection
> 本地视频目录已创建: resource/videos/class_concentration
> 本地视频目录已创建: resource/videos/dynamic_attendance
> 本地视频目录已创建: resource/face_bank
> created: <pipeline_module.video_modules.VideoModule object at 0x000001C88BE9C908>
> created: <pipeline_module.yolo_modules.YoloV5Module object at 0x000001C88BE9CB48>
> C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\site-packages\torch\nn\modules\module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ..\c10/core/TensorImpl.h:1156.)
> return forward_call(*input, **kwargs)
> created: <pipeline_module.pose_modules.AlphaPoseModule object at 0x000001C8A57E3EC8>
> created: <pipeline_module.classroom_action_module.CheatingActionModule object at 0x000001C8A5910E08>
> created: <pipeline_module.vis_modules.CheatingDetectionVisModule object at 0x000001C8A591A9C8>
> starting modules <pipeline_module.yolo_modules.YoloV5Module object at 0x000001C88BE9CB48>
> starting modules <pipeline_module.pose_modules.AlphaPoseModule object at 0x000001C8A57E3EC8>
> starting modules <pipeline_module.classroom_action_module.CheatingActionModule object at 0x000001C8A5910E08>
> starting modules <pipeline_module.vis_modules.CheatingDetectionVisModule object at 0x000001C8A591A9C8>
> 视频源帧率: 30.0
> Exception ignored in: <function Image.**del** at 0x000001C8FEE22948>
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter__init__.py", line 3507, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Exception ignored in: <function Image.**del** at 0x000001C8FEE22948>
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter__init__.py", line 3507, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Exception ignored in: <function Image.**del** at 0x000001C8FEE22948>
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter__init__.py", line 3507, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Exception ignored in: <function Image.**del** at 0x000001C8FEE22948>
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter__init__.py", line 3507, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Exception ignored in: <function Image.**del** at 0x000001C8FEE22948>
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter__init__.py", line 3507, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Exception ignored in: <function Image.**del** at 0x000001C8FEE22948>
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter__init__.py", line 3507, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Exception ignored in: <function Image.**del** at 0x000001C8FEE22948>
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter__init__.py", line 3507, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Exception ignored in: <function Image.**del** at 0x000001C8FEE22948>
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\tkinter__init__.py", line 3507, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Tcl_AsyncDelete: async handler deleted by the wrong thread

12帧不是代码里设置，要自己用软件降低视频文件的帧率。

**Comment by 3019234115** [comment]
我是用摄像头的，输入视频一直报错：
本地视频目录已创建: resource/videos/cheating_detection
本地视频目录已创建: resource/videos/class_concentration
本地视频目录已创建: resource/videos/dynamic_attendance
本地视频目录已创建: resource/face_bank
created: <pipeline_module.video_modules.VideoModule object at 0x000002687B97C908>
created: <pipeline_module.yolo_modules.YoloV5Module object at 0x000002687B97CB48>
C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\site-packages\torch\nn\modules\module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return forward_call(*input, **kwargs)
created: <pipeline_module.pose_modules.AlphaPoseModule object at 0x000002687A094EC8>
created: <pipeline_module.classroom_action_module.CheatingActionModule object at 0x000002680640FE08>
created: <pipeline_module.vis_modules.CheatingDetectionVisModule object at 0x0000026806418A08>
starting modules <pipeline_module.yolo_modules.YoloV5Module object at 0x000002687B97CB48>
starting modules <pipeline_module.pose_modules.AlphaPoseModule object at 0x000002687A094EC8>
starting modules <pipeline_module.classroom_action_module.CheatingActionModule object at 0x000002680640FE08>
starting modules <pipeline_module.vis_modules.CheatingDetectionVisModule object at 0x0000026806418A08>
视频源帧率:  29.55502668311399
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lenovo\Desktop\smart_classroom_demo-master\pipeline_module\core\base_module.py", line 102, in _run
    execute_result = self.process_data(task_data.data) if execute_condition else task_data.task_flag
  File "C:\Users\lenovo\Desktop\smart_classroom_demo-master\pipeline_module\yolo_modules.py", line 13, in process_data
    data.detections = self.detector.detect(data.frame)
  File "C:\Users\lenovo\Desktop\smart_classroom_demo-master\models\yolo_detector.py", line 76, in detect
    pred = self.model(img)[0]
  File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/yolo.py", line 41, in forward
    _30 = (_12).forward((_13).forward(_29, ), _27, )
    _31 = (_10).forward((_11).forward(_30, ), )
    _32 = (_8).forward((_9).forward(_31, ), _26, )
           ~~~~~~~~~~~ <--- HERE
    _33 = (_7).forward(_32, )
    _34 = (_5).forward((_6).forward(_33, ), _31, )
  File "code/__torch__/models/common/___torch_mangle_142.py", line 9, in forward
    argument_1: Tensor,
    argument_2: Tensor) -> Tensor:
    input = torch.cat([argument_1, argument_2], 1)
            ~~~~~~~~~ <--- HERE
    return input

Traceback of TorchScript, original code (most recent call last):
D:\Projects\PyCharmProjects\ComputerVision\yolov5\models\common.py(210): forward
D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py(860): _slow_forward
D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py(887): _call_impl
D:\Projects\PyCharmProjects\ComputerVision\yolov5\models\yolo.py(152): forward_once
D:\Projects\PyCharmProjects\ComputerVision\yolov5\models\yolo.py(121): forward
D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py(860): _slow_forward
D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py(887): _call_impl
D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\jit\_trace.py(940): trace_module
D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\jit\_trace.py(742): trace
D:/Projects/PyCharmProjects/ComputerVision/yolov5/models/export.py(85): <module>
RuntimeError: Sizes of tensors must match except in dimension 2. Got 135 and 136 (The offending index is 0)

**Comment by hongyaohongyao** [comment]
> 我是用摄像头的，输入视频一直报错：
> 本地视频目录已创建: resource/videos/cheating_detection
> 本地视频目录已创建: resource/videos/class_concentration
> 本地视频目录已创建: resource/videos/dynamic_attendance
> 本地视频目录已创建: resource/face_bank
> created: <pipeline_module.video_modules.VideoModule object at 0x000002687B97C908>
> created: <pipeline_module.yolo_modules.YoloV5Module object at 0x000002687B97CB48>
> C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\site-packages\torch\nn\modules\module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ..\c10/core/TensorImpl.h:1156.)
> return forward_call(*input, **kwargs)
> created: <pipeline_module.pose_modules.AlphaPoseModule object at 0x000002687A094EC8>
> created: <pipeline_module.classroom_action_module.CheatingActionModule object at 0x000002680640FE08>
> created: <pipeline_module.vis_modules.CheatingDetectionVisModule object at 0x0000026806418A08>
> starting modules <pipeline_module.yolo_modules.YoloV5Module object at 0x000002687B97CB48>
> starting modules <pipeline_module.pose_modules.AlphaPoseModule object at 0x000002687A094EC8>
> starting modules <pipeline_module.classroom_action_module.CheatingActionModule object at 0x000002680640FE08>
> starting modules <pipeline_module.vis_modules.CheatingDetectionVisModule object at 0x0000026806418A08>
> 视频源帧率: 29.55502668311399
> Exception in thread Thread-2:
> Traceback (most recent call last):
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\threading.py", line 926, in _bootstrap_inner
> self.run()
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\threading.py", line 870, in run
> self._target(*self._args, **self._kwargs)
> File "C:\Users\lenovo\Desktop\smart_classroom_demo-master\pipeline_module\core\base_module.py", line 102, in _run
> execute_result = self.process_data(task_data.data) if execute_condition else task_data.task_flag
> File "C:\Users\lenovo\Desktop\smart_classroom_demo-master\pipeline_module\yolo_modules.py", line 13, in process_data
> data.detections = self.detector.detect(data.frame)
> File "C:\Users\lenovo\Desktop\smart_classroom_demo-master\models\yolo_detector.py", line 76, in detect
> pred = self.model(img)[0]
> File "C:\Users\lenovo\Anaconda3\envs\smartdemo\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
> return forward_call(*input, **kwargs)
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript, serialized code (most recent call last):
> File "code/**torch**/models/yolo.py", line 41, in forward
> _30 = (_12).forward((_13).forward(_29, ), _27, )
> _31 = (_10).forward((_11).forward(_30, ), )
> _32 = (_8).forward((_9).forward(_31, ), _26, )
> ~~~~~~~~~~~ <--- HERE
> _33 = (_7).forward(_32, )
> _34 = (_5).forward((_6).forward(_33, ), _31, )
> File "code/**torch**/models/common/___torch_mangle_142.py", line 9, in forward
> argument_1: Tensor,
> argument_2: Tensor) -> Tensor:
> input = torch.cat([argument_1, argument_2], 1)
> ~~~~~~~~~ <--- HERE
> return input
> 
> Traceback of TorchScript, original code (most recent call last):
> D:\Projects\PyCharmProjects\ComputerVision\yolov5\models\common.py(210): forward
> D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py(860): _slow_forward
> D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py(887): _call_impl
> D:\Projects\PyCharmProjects\ComputerVision\yolov5\models\yolo.py(152): forward_once
> D:\Projects\PyCharmProjects\ComputerVision\yolov5\models\yolo.py(121): forward
> D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py(860): _slow_forward
> D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py(887): _call_impl
> D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\jit_trace.py(940): trace_module
> D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\jit_trace.py(742): trace
> D:/Projects/PyCharmProjects/ComputerVision/yolov5/models/export.py(85):
> RuntimeError: Sizes of tensors must match except in dimension 2. Got 135 and 136 (The offending index is 0)

已知有效视频尺寸为640x480或800x480，其他的目标检测时可能会出错
